<a href="https://colab.research.google.com/github/Zharkyn20/PyTorch/blob/main/PytorchCHCourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reshaping



In [ ]:
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

Change the view


In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
x_squeezed = x.squeeze()
x_squeezed

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = torch.arange(1,10)
y, y.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
y.squeeze()


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = torch.randn(2, 3, 5)
x.size(), x

(torch.Size([2, 3, 5]),
 tensor([[[ 1.8749,  1.5322,  3.0204, -2.6004,  1.8911],
          [ 0.1157, -0.8364, -1.0474,  0.0611, -0.5684],
          [-0.1637, -0.5705, -0.9781, -1.9922,  1.6114]],
 
         [[ 0.0355,  1.3127, -0.1631, -1.2329,  0.8266],
          [ 0.0767, -0.0524,  0.3951,  0.1592,  1.0043],
          [ 1.0769, -0.9797,  0.0893, -0.5116,  0.0167]]]))

In [ ]:


x_permuted = torch.permute(x, (2, 0, 1))
x_permuted

tensor([[[ 1.8749,  0.1157, -0.1637],
         [ 0.0355,  0.0767,  1.0769]],

        [[ 1.5322, -0.8364, -0.5705],
         [ 1.3127, -0.0524, -0.9797]],

        [[ 3.0204, -1.0474, -0.9781],
         [-0.1631,  0.3951,  0.0893]],

        [[-2.6004,  0.0611, -1.9922],
         [-1.2329,  0.1592, -0.5116]],

        [[ 1.8911, -0.5684,  1.6114],
         [ 0.8266,  1.0043,  0.0167]]])

In [ ]:
x_permuted[0, 0, 0] = 555
x_permuted

tensor([[[ 5.5500e+02,  1.1568e-01, -1.6370e-01],
         [ 3.5491e-02,  7.6749e-02,  1.0769e+00]],

        [[ 1.5322e+00, -8.3645e-01, -5.7055e-01],
         [ 1.3127e+00, -5.2436e-02, -9.7970e-01]],

        [[ 3.0204e+00, -1.0474e+00, -9.7811e-01],
         [-1.6307e-01,  3.9508e-01,  8.9299e-02]],

        [[-2.6004e+00,  6.1096e-02, -1.9922e+00],
         [-1.2329e+00,  1.5919e-01, -5.1157e-01]],

        [[ 1.8911e+00, -5.6840e-01,  1.6114e+00],
         [ 8.2663e-01,  1.0043e+00,  1.6717e-02]]])

In [ ]:
x = torch.arange(1, 10).reshape([1, 3, 3])

In [ ]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0]

tensor([1, 2, 3])

In [ ]:
x[0, 0, 0]

tensor(1)

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, :2, 1]

tensor([[2, 5]])

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])