<a href="https://colab.research.google.com/github/Zharkyn20/PyTorch/blob/main/notes/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1

In [ ]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tenxor = torch.ones(7)
numpy_tenxor = tenxor.numpy()
tenxor, numpy_tenxor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tenxor = tenxor + 1
tenxor, numpy_tenxor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility


In [ ]:
torch.rand(3, 3)

tensor([[0.3191, 0.7392, 0.9986],
        [0.6637, 0.5883, 0.6997],
        [0.5718, 0.8311, 0.6604]])

In [ ]:
random_a = torch.rand(3,4)
random_b = torch.rand(3, 4)

print(random_a)
print(random_b)
print(random_a == random_b)

tensor([[0.7127, 0.3857, 0.9351, 0.0495],
        [0.9469, 0.2884, 0.5358, 0.1908],
        [0.9634, 0.1729, 0.2896, 0.4335]])
tensor([[0.7678, 0.0653, 0.8310, 0.5723],
        [0.3293, 0.8956, 0.6362, 0.2943],
        [0.6667, 0.3811, 0.5859, 0.2452]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Random but reproducible tensors

In [ ]:
random_seed = 1234567890
torch.manual_seed(random_seed)
random_c = torch.rand(4, 2)

torch.manual_seed(random_seed)
random_d = torch.rand(4, 2)

print(random_c)
print(random_d)
print(random_c == random_d)

tensor([[0.4115, 0.1703],
        [0.4556, 0.1519],
        [0.5030, 0.5041],
        [0.2636, 0.5436]])
tensor([[0.4115, 0.1703],
        [0.4556, 0.1519],
        [0.5030, 0.5041],
        [0.2636, 0.5436]])
tensor([[True, True],
        [True, True],
        [True, True],
        [True, True]])


Running tensors on gpus; make faster calculations